config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "games#index"

  resources :messages, only: [ :create ]

  resources :games, only: [ :index, :create, :show, :new ]

  namespace :api do
    resources :messages, only: [ :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :users
  has_many :messages, dependent: :destroy

  validates :status, inclusion: [ "waiting", "playing", "finished" ]

  scope :active, -> { where(status: [ "waiting", "playing" ]) }

  def system_prompt
    "The user is guessing a number (1-100). The number is #{secret_number}. Without telling the user the secret number, give them a hint from popular culture if they guess incorrectly"
  end

  def formatted_messages(user)
    [ { role: "system", content: system_prompt } ] + user_messages(user).formatted
  end

  def initiate
    users.each do |user|
      text = "Lets Play! You are Player #{player_number(user)}"
      Message.create(role: "assistant", text:, user:).send_to_user

      text = "Guess the secret number (1-100)"
      Message.create(role: "assistant", text:, user:).send_to_user
    end
  end

  def secret_number
    ((created_at.to_i % 100) + 1).to_s
  end

  def handle_status(message)
    if status == "waiting"
      message.user.reply("Waiting for more players (#{users.count}/4)")
    elsif status == "finished"
      message.user.reply("This game is already over")
    elsif status == "playing"
      play(message)
    end
  end

  def play(message)
    if message.text == secret_number
      declare_winner(message.user)
    else
      hint(message.user)
    end
  end

  def declare_winner(winner)
    update(status: "finished")

    users.each do |user|
      if user == winner
        user.reply("Congratulations Player #{player_number(user)}, you win!!")
      else
        user.reply("Better luck next time, Player #{player_number(winner)} got the answer (#{secret_number}) first.")
      end
    end

    users.update_all(game_id: nil)
  end

  def player_number(user)
    users.ids.index(user.id)
  end

  def user_messages(user)
    messages.where(user:)
  end

  def hint(user)
    user.reply(response(user))
  end

  def chat(user)
    OpenAI::Client.new.chat(
      parameters: {
        model: "gpt-4o",
        messages: formatted_messages(user),
        temperature: 0.5
      }
    )
  end

  def response(user)
    chat(user).dig("choices", 0, "message", "content")
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :game, optional: true

  validates :text, presence: true
  validates :role, inclusion: [ "user", "assistant" ]

  def self.formatted
    all.map { |message| { role: message.role, content: message.text } }
  end

  def send_to_user
    return unless user.telegram_id

    token = ENV.fetch("TELEGRAM_TOKEN")

    url = "https://api.telegram.org/bot#{token}/sendMessage"
    json = { text:, chat_id: user.telegram_id }

    HTTP.post(url, json:)
  end

  def handle
    if text.include?("/create")
      user.create_game
    elsif text.include?("/leave")
      user.leave_game
    elsif text.include?("/join")
      user.join_game
    elsif match = text.match(/\A\d{4}\z/)
      user.join_code(match[0])
    elsif !user.game
      user.welcome
    else
      user.game.handle_status(self)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :game, optional: true

  def notify_already_playing
    if game
      reply("You are already in game #{game.code}. Message /leave to leave")
    end
  end

  def create_game
    return notify_already_playing if game

    update(game: Game.create(status: "waiting", code: rand(1000..10000)))
    reply("Game created, share the game code #{game.code} to let players join")
  end

  def join_game
    return notify_already_playing if game

    reply("Enter the code for the game you want to join")
  end

  def join_code(code)
    return notify_already_playing if game

    found_game = Game.find_by(code:)

    return reply("Could not find that game") unless found_game
    return reply("This game is not available to join") unless found_game.status == "waiting"

    update(game: found_game)

    reply("Welcome to game #{game.code}. Waiting for players to join (#{game.users.count}/4 players).")

    if game.users.count > 3
      game.update(status: "playing")
      game.initiate
    end
  end

  def leave_game
    return reply("You are not in a game") unless game

    previous_game = game
    update(game: nil)
    previous_game.destroy if previous_game.users.none?

    reply("You have left game #{previous_game.code}")
  end

  def welcome
    reply("Welcome to the chatbot game. type /create to make a new game")
  end

  def reply(text)
    messages.create(role: "assistant", text:, game:).send_to_user
  end
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ActionController::API
  def create
    telegram_id = params["message"]["from"]["id"].to_s
    user = User.find_or_create_by(telegram_id: telegram_id)
    message = user.messages.create(role: "user", text: params["message"]["text"], game: user.game)
    message.handle

    render json: { message: message, messages: Message.includes(:user).as_json(include: :user) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @game = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.create(status: "playing", code: rand(1000..10000))
    @game.users << [ User.create, User.create, User.create, User.create ]
    @game.initiate

    redirect_to game_path(@game)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    user = User.find_or_create_by(id: params[:message][:user_id])
    text = params[:message][:text]

    message = user.messages.create(role: "user", text:, game: user.game)
    message.handle

    redirect_to user.game
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h4>Games</h4>
<div>
  <%= link_to "New Game", new_game_path %>
  <%= button_to "Create Game", games_path, class: "mt-2" %>
</div>
<ul class="mt-4">
  <% Game.all.each do |game| %>
    <li>
      <%= link_to game.id, game_path(game)%>
    </li>
  <% end %>
</ul>

app/views/games/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <p>type /create to start a game</p>
      <%= form_with model: Message.new do |form| %>
        <%= form.hidden_field :user_id, value: rand(10000) %>
        <%= form.text_area :text, class: "form-control" %>
        <%= form.submit "Send", class: "btn btn-primary mt-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="container">
  <div class="row">
    <% @game.users.each do |user| %>
      <div class="col-md-3 mt-5">
        <h4><%= user.id %></h4>
        <div class="card p-2 message-card">
          <% user.messages.each do |message| %>
            <p class=<%= message.role == "assistant" ? "text-primary" : "" %>><%= message.text %></p>
          <% end %>
        </div>
        <%= form_with model: user.messages.new do |form| %>
          <%= form.hidden_field :user_id, value: user.id %>
          <%= form.text_area :text, class: "form-control" %>
          <%= form.submit "Send", class: "btn btn-primary mt-2" %>
        <% end %>
      </div>
    <% end %>
    <% if @game.users.count < 4 %>
      <% user_id = rand(10000) %>
      <div class="col-md-3 mt-5">
        <h4><%= user_id %></h4>
        <div class="card p-2 message-card"></div>
        <%= form_with model: Message.new do |form| %>
          <%= form.hidden_field :user_id, value: user_id %>
          <%= form.text_area :text, class: "form-control" %>
          <%= form.submit "Send", class: "btn btn-primary mt-2" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Chatbot Game" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>